# Generated by Django 3.1.7 on 2021-03-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.TextField(blank=True)),
                ('dish', models.TextField(blank=True)),
            ],
        ),
    ]
